services:
  solarops-api:
    build: .
    container_name: solarops_api
    ports:
      - "8000:8000"
    volumes:
      - ./phase_04_mlops/logs:/app/phase_04_mlops/logs
      - ./data/vector_store:/app/data/vector_store
    env_file:
      - .env
    restart: always
